### PR TITLE
New image.

### PR DESCRIPTION
**Pull request by lincolncosta**
Added new image (pic 4).

### CODE REVIEW

**Comment by srbcheema1** [comment]
thanks for the PR @tekpixo 
picture is great :)
there are two issues 
1. dimensions are not as required . dimensions required are 960 * 960 for big image .
     ...........................120*120 for cutouts 
2. your commit also have conflicts as someone has already added a picture of name "pic 4"
.......................................you may rename it to "pic6" 
i will be waiting eagerly for your next commit :)

**Comment by lincolncosta** [comment]
Hey @srbcheema1, sorry for the last picture with the wrong dimensions, hope this new image is ok.

**Comment by srbcheema1** [comment]
@tekpixo 
really sorry to interrupt again but slice 3 and slice 2 are totally identical
 that may create confusion to player

**Comment by srbcheema1** [comment]
please read contributing.md file

**Comment by srbcheema1** [comment]
thanks for the PR :+1: 
you have done excellent job :1st_place_medal: 
i would love to see more contribution from your side

**Comment by lincolncosta** [comment]
Sorry for the miss communication and the problems with the images. I was think about the game itself crop and save all the images slices, what do you think?

**Pull request merged**
