### PR TITLE
Add texture photo & cute kitten

### LINKED ISSUE #9: update images used in the game
contributers for hactoberfest are welcome to update the images in the game 
just be careful with the dimentions of new images you add .
any kind of contibution is accepted

### PR DESCRIPTION
**Pull request by maitreyav**
Photo by Tools For Motivation on Unsplash

https://unsplash.com/photos/cmR92mJs40w

Resolves #9

### CODE REVIEW

**Comment by srbcheema1** [comment]
thanks for the PR @maitreyav 
your pic9 is really awesome and pic10 is also cute .
but there is a problem pic10 is blurr from top and bottom . this will create a confussion for the player to where the slice will go .
i would like you to change pic10 .
i am eager to merge your PR :)

**Comment by maitreyav** [comment]
@srbcheema1, Welcome! Glad that you liked it. I also have a non-edited version of pic10 which I think will go well.

**Comment by srbcheema1** [comment]
yes . but try that slices should be different from each other . so that player may distinguish them easily

**Comment by srbcheema1** [comment]
thanks for the PR @maitreyav 
you have done perfect work :+1:

**Comment by maitreyav** [comment]
You're welcome, @srbcheema1! I'll be happy to contribute more, with my photos. 😄  I think we should add "Add to Homescreen" ability, what are your views on it?

**Pull request merged**
