### PR TITLE
[Issue 9] Added pic5: Lion

### PR DESCRIPTION
**Pull request by AliaksandrY**

### CODE REVIEW

**Comment by maitreyav** [comment]
I'd like to work on it

**Comment by srbcheema1** [comment]
@OMGHaveFun 
picture is awesome :heart_eyes: 
you have done excellent job :1st_place_medal: 
i would love to see more contributions from your side :)

**Comment by srbcheema1** [comment]
@OMGHaveFun 
can you add a contribution.md file so that others can read and contribute with perfections 
because many other contributers are just sending PR without keeping dimensions in mind .
and i will be glad if you give  a STAR to this repository

**Comment by AliaksandrY** [comment]
@srbcheema1 
I would add some pictures bit later today
About contribution, you can add new issue for this, add Hacktoberfest label for it ) and assign for me

**Comment by srbcheema1** [comment]
ok @OMGHaveFun

**Pull request merged**
